version: '3.8'
services:
  client:
    build: statistic/client/
    ports:
      - "9090:9090"
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:8081

  ewm-service:
    build:   ewm-service/
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STAT_SERVER_URL=http://client:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    build: statistic/server/
    ports:
      - "8081:8081"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root


  stats-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-stats-db
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  ewm-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-main-db
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
